#+TITLE: TGAME
* Tabletop Gaming: Assorted and Malleable Experiences Official Repository

  Contact: unlvtoda@gmail.com
  
** Why organize?

  Players are at the very core of tabletop games.
  At a minimum, playing tabletop games requires finding space and time to play and ensuring that players have something to do.
  This ensures that players can interact with each other in a comfortable setting, whether that means interacting with new people, discussing new board game ideas, or just having a comfortable space to meet with old friends.
  Meeting these essential functions on an ongoing basis requires establishing an organizational structure and a way to gather necessary resources.
  
  As more and more players gather to play, the social interactions also provide unique opportunities for players to collaborate, to teach and learn from each other, to create their own experiences, and to design and test new board games.
  Up until now, there has been no effective way to house, support, and develop player's various interests.
  Establishing an organization is therefore necessary to meet ongoing essential functions of playing tabletop games together as well as support those who want to collaborate and turn their ideas into something more tangible.
  Whatever the reason, establishing an organization provides a way to support each player's various interests.
    
** Why GitHub?

  The purpose of this GitHub repository is to host all the files required for establishing, maintaining, and working on the organization.
  GitHub is a collaborative tool that allows multiple users to interact with, share, discuss, and modify files, important documents, and ideas. 
  
  Typically, GitHub is used to host complex computer code projects that have many moving parts and people. 

  GitHub is the most transparent way to track all moving parts, with all considerations from all users and to best integrate them into the documentation.

** Getting Started on Providing Feedback (and Choosing Your Level of Involvement)

You have two options to get started:

*** Suggestion Box
You can submit a response in the suggestion box. Anyone may use the suggestion box anonymously, so please provide your sincere feedback! 

After submission, we will make an issue with the request so that the issue can be tracked publicly.

[[https://forms.gle/vPe3dBW6jM1tnogB6][Suggestion Box]]

*** Submitting Issues

Issues are the primary way that requests, concerns, enhancements, and suggestions are handled.

To get started, create an account and open an issue in this repository.  To open an issue:

1. Click the '[[https://github.com/calebjpicker/TODA/issues][Issues]]' tab.  
2. Click the green button labeled 'New Issue'.
3. Type a detailed title.
4. Type a detailed description.
5. Click 'Submit new issue'.

Either you or we will add additional labels to categorize the issue.
Then anyone can comment and discuss the issue, and the entire discussion thread is publicly visible.

** Doing More
*** Forks and Pull Requests
If you want to directly contribute to documentation, you can 'fork' this repository.
A fork refers to copying this repository to your account.
You make a copy, then you are free to make any changes you want.
Eventually you can make a 'pull request' so that those changes can be reviewed.
Like issues, anyone can comment and discuss the pull request and finalize it.

To fork the repository:

1. On the repository page, click the button in the upper-right hand corner that says, 'fork'. GitHub will copy the repo to your account.
2. Create or edit files as you'd like.
3. Make a pull request by clicking 'New pull request'.
4. Fill out the title and description, like issues.
5. Click 'Create pull request'.

The community will then review and discuss.

*** Projects
Projects are used as a way to organize and implement large functions of the organization. Tasks, issues, and pull requests are organized within projects.

If you would like to get involved and manage one or more projects, please contact Rudy or Caleb.
