#+TITLE: TODA
* Tabletop Organization for Data, Design and Application Official Repository


*** Why organize?

    We are growing. 2 years ago we started with only 4 people! Now we have more than 16 people and counting coming to board game nights.
    We attract new people, and we need a way to account for that.
    You were new once, and every one of you changed the group's dynamic when you came in.
    going forward, each new person will continue to change the group dynamic.

    Playing board games requires many resources and a way to allocate those resources as best as possible.
    When there are many people you need to ensure that there's adequate space to play, there's time to play them, and that everyone has something to do.
    Each person's needs and interests should to be assesed. 
    Information needs to be communicated effectively
    We need an efficient way to satisfy these functions.  

    With 4-6 people doing all of this takes less effort.
    However, our group will grow to potentially 30+ people.
    With groups that grow, we still need to maintain the essential functions of the group: ensuring adequate spece, ensuring there is time to play, and ensuring that everyone gets informed.
    This will become increasingly difficult without organization.

    
    Rudolf Jovero and Caleb Picker have been developing TODA since Fall 2017 to address the every growing and change nature of the group.

*** Why GitHub?

The purpose of this GitHub repository is to host all the files required for establishing, maintaining, and tweaking the organization.
GitHub is a collaborative tool that allows multiple users to interact with, share, discuss, and modify files, important documents, and ideas. 
  
Typically, GitHub is used to host complex computer code projects that have many moving parts and people. 

GitHub is the clearest way to track all moving parts, with all considerations from all users and best integrate them into the documentation.

** Getting Started

GitHub has many features.
One commonly used feature is called issues.
Issues are the primary way that requests, concerns, enhancements and suggestions are handled.

To get started, just open an issue.  To open an issue:

1. Click the '[[https://github.com/calebjpicker/TODA/issues][Issues]]' tab.  
2. Click the green button labeled 'New Issue'.
3. Type a detailed title.
4. Type a detailed description.
5. Click 'Submit new issue'.

Either you or we will add additional labels to categorize the issue.
Then anyone can comment and discuss the issue, and the entire discussion thread is visible.

** Doing More
*** Forks and Pull Requests
If you want to directly contribute to documentation, you can 'fork' this repository to your account.
A fork refers making a copy of this repository to your account.
You make a copy, then you are free to make any changes you want.
Eventually you can make a 'pull request' so that those changes can be reviewed.
Like issues anyone can comment and discuss the pull request and finalize it.
To fork the repository:

1. on the repository page, click the upper right hand button that says 'fork' and github will copy it to your account.
2. edit files as you'd like.
3. make a pull request by clicking 'New pull request'.
4. fill out the title and description like issues.
5. Click 'Create pull request'.

the community will then review and discuss.

*** Projects
Projects are used as a way to organize and implement large functions of the organization. Tasks, issues, and pull requests are organized within projects.

If you would like to get involved and manage one or more projects, please contact Rudy or Caleb.
