In order for this group to run, we need someone who...
* Facilitation

** Funds 

# External
   Reaches out to businesses and departments
   Arguing Budget
# Internal
   Maintains relationships in the group, and appropriate behavior

# Treasurer
   Logs financial resources as they come in and get spent.
   Creating budgets

   Compliance with rules club is subject to outside of the organization
   
   Logs meeting information, and any other kind of information.
** Resources
   Human Resource
   Rooms
   Boards Games
   Pieces
   Food

** Communication/Scheduling

   Logistics
   ensures that games and resources get to places.
   ensures people understand the boundaries of acceptable behavior. Etiquitte
   Room Scheduling
   Game schedules
   Catering
   Marketing/Outreach
   Survey data

** Disciplinary
   
** Biome Needs   
   Awareness of other biomes and communication to those biomes.
   Must know about their biomes, and other biomes, and can communicate to other biomes.
   Ensuring resources are avialable to support functions
*** Game Design Biome 
*** Game Discussion
*** Social Life
*** Status
*** Education
*** Self Improvement
*** 

* Facilitator section of the consitution
** Article preamble, II-III (Caleb)
Revise, take kevin's notes into consideration, Pillar define preamble
For the preamble, determine how the organization can support the proposed functions
For the Article II pillars, determine how the pillars relate to or support the organization's function
For Article III (authority), skim through relevant RSO documents to determine whether these documents give organization relevant authority and then revise accordingly

** Article IV, Section 2 (Rudy)
   Comply with RSO and UNLV
   Biome, Tasks to be completed, Which tasks should be grouped together so they are managed.
   Financial Organization and tracking Well defined
   
   Flexible to permit members to contribute to tasks.
   
   * Flexible for members to come in and out of tasks, allow redundancy, so tasks don't fall on one person's shoulders.
   
   Graceful Degredation
   
   Ensure Transparency, and knowldege of their tasks.
   
   Determine which resources are necessary to conduct tasks
   
   Communication to other facilitators should be clear.
   
   Tasks could be enforced in pairs (spearhead, handle).
   
   Task Board: Task proposal(Thumbs up), Task signup, Task Completion

*** Qualifications
*** Duties
*** Appointments (Election Possibly)
*** Inaugural Board

** Article V Meetings (Caleb)
Section I, what kind of space/resource allocations do we want for a meeting in the long term?
   presentations, discussion groups, lectures, board game design, playtest
   discussion area
   announcements 
Section II are facilitation meetings
   read through section II as it is currently (copied from a website)
   agenda is available at least one week in advance
   meeting times are determined a semester in advance (maybe not a full semester)
      option for calling impromptu/urgent meetings
   simplify this section (don't need to be a paragraph long), consider bullet points
   keep in mind something that will guarantee that facilitator meetings will be done in a timely manner
   add in someting about what chairperson does
      chairperson guides the meeting through agenda
     simplify subsection V and VI
   Subsection VII suggestion box, it's place in meeting is symbolic and shows we are taking community suggestions into account before any and all other business
   consider changing subheadings (e.g., remove subsection so that it aligns iwth rest of document)
** Article VI
   we can work on this at a later date
